Learning path index search 01 Updates
neomatrix369/learning-path-index pull request #21
Opened 2023-11-05 03:50 UTC by mbhoge

2023-11-06 16:55 UTC, neomatrix369 requested changes
One small change I would request - can you pls rename the folder `rag-search` to `llm-poc-variant-01` or something in this form, and add a link from the main README that links to this sub-folder in the project

Just renaming the folder for the moment would be a good first step.
I dont see the `.env_template` file, see https://github.com/mbhoge/kagglex-final-project/blob/main/.env_template - without which the README instructions might not be correct.

Im trusting this works out of the box?

2023-11-06 16:56 UTC, neomatrix369 commented
Good work @mbhoge and thank you! Just small changes requested.

2023-11-07 07:48 UTC, mbhoge commented
Made the following changes: 

1. Renamed the rag-search to llm-poc-variant-02
2. Added the .env_template file
3. Updated the main README.md to reference the Contextual Search project.

2023-11-07 13:23 UTC, neomatrix369 requested changes
Looks good except you might have not deleted the `rag-search` folder from your git history (and your local repo) and pushed it to the remote repo

2023-11-07 17:11 UTC, mbhoge commented
Good catch @neomatrix369 I deleted the folder from GitHub.

2023-11-07 22:33 UTC, neomatrix369 approved these changes
LGTM

It would be good to get this one tested for a new user just for our sanity

Merging it for now!

2023-11-07 22:33 UTC, merged